on:
  release:
    types:
      - published

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Major Enhancements 🎉
      labels:
        - enhancement-major
    - title: Minor Enhancements 💄
      labels:
        - enhancement-minor
    - title: Bug fixes 🔨
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'
