exclude = [".ruff_cache", ".venv", "__pypackages__", "__pycache__"]
indent-width = 4
line-length = 88
show-fixes = true
target-version = "py310"

[lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
extend-select = ["ALL"]
ignore = [
  "ANN002", # Type annotation for *args
  "ANN003", # Type annotation for **kwargs
  "ANN101", # Type annotation for self
  "ANN102", # Type annotation for cls
  "ANN206", # Return type annotation for classmethod
  "ANN401", # Dynamically typed expressions
  "D100",   # Docstring in public module
  "D101",   # Docstring in public class
  "D102",   # Docstring in public method
  "D103",   # Docstring in public function
  "D104",   # Docstring in public package
  "D105",   # Docstring in magic method
  "D106",   # Docstring in public nested class
  "D107",   # Docstring in __init__ method
  "D203",   # Incompatible with D211
  "D213",   # Incompatible with D212
]

[format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[lint.isort]
lines-between-types = 1
