dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
exclude = [".ruff_cache", ".venv", "__pypackages__", "node_modules", "venv"]
extend-select = [
  "A",
  "ANN",
  "ARG",
  "ASYNC",
  "B",
  "BLE",
  "C",
  "C4",
  "C90",
  "COM",
  "CPY",
  "D",
  "DJ",
  "DTZ",
  "E",
  "EM",
  "ERA",
  "EXE",
  "F",
  "FA",
  "FBT",
  "FIX",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "LOG",
  "N",
  "NPY",
  "PD",
  "PGH",
  "PIE",
  "PL",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "RUF",
  "S",
  "SIM",
  "SLF",
  "SLOT",
  "T10",
  "T20",
  "TCH",
  "TD",
  "TID",
  "TRIO",
  "TRY",
  "UP",
  "W",
  "YTT",
]
ignore = [
  "ANN002", # Type annotation for *args
  "ANN003", # Type annotation for **kwargs
  "ANN101", # Type annotation for self
  "ANN102", # Type annotation for cls
  "ANN206", # Return type annotation for classmethod
  "ANN401", # Dynamically typed expressions
  "ERA001", # Commented-out code
  "D100",   # Docstring in public module
  "D101",   # Docstring in public class
  "D102",   # Docstring in public method
  "D103",   # Docstring in public function
  "D104",   # Docstring in public package
  "D105",   # Docstring in magic method
  "D106",   # Docstring in public nested class
  "D107",   # Docstring in __init__ method
  "D203",   # Incompatible with D211
  "D213",   # Incompatible with D212
  "S311",   # Pseudo-random generators
  "T203",   # pprint()
]
line-length = 88
show-fixes = true
target-version = "py310"

[isort]
lines-between-types = 1
